name: Deploy Arch

on:
  release:
    types: [released]

jobs:
  arch:
    name: Deploy Arch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate PKGBUILD
        run: sys/arch/pkgbuild.sh "${{ github.event.release.tag_name }}" > sys/arch/PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: replay-sorcery
          pkgbuild: sys/arch/PKGBUILD
          commit_username: matanui159
          commit_email: josh@minteronline.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
