name: CI
on: [push, pull_request]

jobs:
  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update package repositories
        run: sudo apt-get update

      - name: Install FFmpeg
        run: sudo apt-get install -y
          libavutil-dev
          libavformat-dev
          libavdevice-dev
          libavcodec-dev
          libavfilter-dev

      - name: Configure code
        run: cmake -B bin -DCMAKE_BUILD_TYPE=Release -DRS_WARN_ERROR=ON

      - name: Build code
        run: make -C bin

      - name: Format code
        run: make -C bin clang-format

      - name: Check formatting and ignores
        run: git diff --color --exit-code
